### ISSUE TITLE
Unable to connect at Medium security level

### ISSUE THREAD

**Issue by avoidik** [luckyrat/KeeFox#761]
Firefox 51.0.1 (x32)
KeeFox 1.6.4
KeePass2 2.35
KeePassRPC 1.6.4.0

Keefox unable to connect to KeePassRPC at **Medium KeePass security level**, but able to connect with **High KeePass security level**.

Debug log from KeePassRPC:
```
Fleck says: Error while reading. Exception: Fleck2.WebSocketException: Exception of type 'Fleck2.WebSocketException' was thrown.
   at Fleck2.HandlerFactory.BuildHandler(WebSocketHttpRequest request, Action`1 onMessage, Action onClose, Action`1 onBinary)
   at Fleck2.WebSocketConnection.CreateHandler(IEnumerable`1 data)
   at Fleck2.WebSocketConnection.<>c__DisplayClassb.<Read>b__a(Int32 r)
   at Fleck2.SocketResult.Success[TResult](Action`1 callback)
   at Fleck2.SocketWrapper.<>c__DisplayClass7.<Receive>b__6(SocketResult result)
   at Fleck2.SocketFactory.<>c__DisplayClass16.<DoAsyncTask>b__15(Object )
Fleck says: 299 bytes read
Fleck says: Error while reading. Exception: Fleck2.WebSocketException: Exception of type 'Fleck2.WebSocketException' was thrown.
   at Fleck2.HandlerFactory.BuildHandler(WebSocketHttpRequest request, Action`1 onMessage, Action onClose, Action`1 onBinary)
   at Fleck2.WebSocketConnection.CreateHandler(IEnumerable`1 data)
   at Fleck2.WebSocketConnection.<>c__DisplayClassb.<Read>b__a(Int32 r)
   at Fleck2.SocketResult.Success[TResult](Action`1 callback)
   at Fleck2.SocketWrapper.<>c__DisplayClass7.<Receive>b__6(SocketResult result)
   at Fleck2.SocketFactory.<>c__DisplayClass16.<DoAsyncTask>b__15(Object )
Fleck says: Client connected from 127.0.0.1:53142
Fleck says: 299 bytes read
Fleck says: Error while reading. Exception: Fleck2.WebSocketException: Exception of type 'Fleck2.WebSocketException' was thrown.
   at Fleck2.HandlerFactory.BuildHandler(WebSocketHttpRequest request, Action`1 onMessage, Action onClose, Action`1 onBinary)
   at Fleck2.WebSocketConnection.CreateHandler(IEnumerable`1 data)
   at Fleck2.WebSocketConnection.<>c__DisplayClassb.<Read>b__a(Int32 r)
   at Fleck2.SocketResult.Success[TResult](Action`1 callback)
   at Fleck2.SocketWrapper.<>c__DisplayClass7.<Receive>b__6(SocketResult result)
   at Fleck2.SocketFactory.<>c__DisplayClass16.<DoAsyncTask>b__15(Object )
Fleck says: Client connected from 127.0.0.1:53143
Fleck says: Client connected from 127.0.0.1:53141
Fleck says: 299 bytes read
Fleck says: Error while reading. Exception: Fleck2.WebSocketException: Exception of type 'Fleck2.WebSocketException' was thrown.
   at Fleck2.HandlerFactory.BuildHandler(WebSocketHttpRequest request, Action`1 onMessage, Action onClose, Action`1 onBinary)
   at Fleck2.WebSocketConnection.CreateHandler(IEnumerable`1 data)
   at Fleck2.WebSocketConnection.<>c__DisplayClassb.<Read>b__a(Int32 r)
   at Fleck2.SocketResult.Success[TResult](Action`1 callback)
   at Fleck2.SocketWrapper.<>c__DisplayClass7.<Receive>b__6(SocketResult result)
   at Fleck2.SocketFactory.<>c__DisplayClass16.<DoAsyncTask>b__15(Object )
```

Debug log from KeePass2:
```
Sat Feb 25 2017 19:31:28 GMT+0200 (FLE Standard Time):WARN: An attempt to setup the KPRPC secure channel has failed. It will not be retried for at least 10 seconds. If you see this message regularly and are not sure why, please ask on the help forum. Technical detail about the problem follows: [Exception... "Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]"  nsresult: "0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE)"  location: "JS frame :: resource://kfmod/kprpcClient.js :: this.getNSILMpassword :: line 808"  data: no]
```

Any help appreciated.

**Comment by avoidik** [comment]
Security options set in KeeFox plugin and untouched in KeePassRPC (defaults).

**Comment by avoidik** [comment]
Fixed with new Firefox profile. Dunno what's happened.
